# Libraries

In [1]:
import pandas as pd
import numpy as np

# Dataset

In [13]:
path_file_1 = r"C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\diabetic_data.csv"
path_file_2 = r"C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\IDS_mapping.csv"



df_1 = pd.read_csv(path_file_1)
df_1.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

## Data Cleaning

In [ ]:
df_2 = pd.read_csv(path_file_2)
df_2
df_2['admission_type_id'].unique()
# IDS_mapping file, have 3 tables concatenated

array(['1', '2', '3', '4', '5', '6', '7', '8', nan,
       'discharge_disposition_id', '9', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '30', '27', '28', '29', 'admission_source_id'], dtype=object)

### IDS_mapping data

In [ ]:
# Discover the position of the first occurrence of "discharge_disposition_id" in the "admission_type_id" column
# in 9
id_position_1 = (
    df_2[df_2["admission_type_id"] == "discharge_disposition_id"].index[0]
)
id_position_1

np.int64(9)

In [ ]:
# Repeat the step for another occurrence
# in 41
id_position_2 = (
    df_2[df_2["admission_type_id"] == "admission_source_id"].index[0]
)
id_position_2

np.int64(41)

In [ ]:
# Separate the three tables in the IDS_mapping file based on the discovered positions
admission_type = df_2.iloc[0:id_position_1].copy()
admission_type

  admission_type_id    description
0                 1      Emergency
1                 2         Urgent
2                 3       Elective
3                 4        Newborn
4                 5  Not Available
5                 6            NaN
6                 7  Trauma Center
7                 8     Not Mapped
8               NaN            NaN

In [41]:
admission_type = admission_type.dropna()
admission_type

   admission_type_id    description
0                  1      Emergency
1                  2         Urgent
2                  3       Elective
3                  4        Newborn
4                  5  Not Available
6                  7  Trauma Center
7                  8     Not Mapped

In [52]:
# Rename columns 
admission_type.columns = ["admission_type_id", "admission_type_description"]
admission_type

   admission_type_id admission_type_description
0                  1                  Emergency
1                  2                     Urgent
2                  3                   Elective
3                  4                    Newborn
4                  5              Not Available
6                  7              Trauma Center
7                  8                 Not Mapped

In [53]:
# Return the data type of the 'admission_type_id' to int
admission_type['admission_type_id'] = admission_type['admission_type_id'].astype(int)
admission_type.dtypes

admission_type_id              int64
admission_type_description    object
dtype: object

In [ ]:
# For discharge_disposition
discharge = df_2.iloc[id_position_1 + 1:id_position_2].copy()
discharge = discharge.dropna()
discharge.columns = ['discharge_disposition_id', 'discharge_disposition_description']
discharge['discharge_disposition_id'] = discharge['discharge_disposition_id'].astype(int)
discharge.dtypes

In [60]:
# For admission_source
source = df_2.iloc[id_position_2 + 1:].copy()
source = source.dropna()
source.columns = ['admission_source_id', 'admission_source_description']
source['admission_source_id'] = source['admission_source_id'].astype(int)
source.dtypes

admission_source_id              int64
admission_source_description    object
dtype: object

In [61]:
# Test
discharge
source

    admission_source_id                       admission_source_description
42                    1                                 Physician Referral
43                    2                                    Clinic Referral
44                    3                                       HMO Referral
45                    4                           Transfer from a hospital
46                    5     Transfer from a Skilled Nursing Facility (SNF)
47                    6         Transfer from another health care facility
48                    7                                     Emergency Room
49                    8                              Court/Law Enforcement
50                    9                                      Not Available
51                   10              Transfer from critial access hospital
52                   11                                    Normal Delivery
53                   12                                 Premature Delivery
54                   13                                          Sick Baby
55                   14                                   Extramural Birth
56                   15                                      Not Available
58                   18           Transfer From Another Home Health Agency
59                   19             Readmission to Same Home Health Agency
60                   20                                         Not Mapped
61                   21                                    Unknown/Invalid
62                   22   Transfer from hospital inpt/same fac reslt in...
63                   23                          Born inside this hospital
64                   24                         Born outside this hospital
65                   25            Transfer from Ambulatory Surgery Center
66                   26                              Transfer from Hospice

### Create tables from IDS_mappint data

In [62]:
admission_type.to_csv(r"C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\admission_type.csv", index=False)
discharge.to_csv(r"C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\discharge_disposition.csv", index=False)
source.to_csv(r"C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\admission_source.csv", index=False)

### Data diabetic_data

In [ ]:
df_1.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [ ]:
df_1.dtypes

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object
dtype: object

In [64]:
df_1.duplicated().sum()

np.int64(0)

In [65]:
df_1.isna().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [67]:
# Remove NaN values in the 'max_glu_serum' and 'A1Cresult' columns 
df_1 = (
    df_1
    .fillna(value={'max_glu_serum': 'None', 'A1Cresult': 'None'})
)
df_1.isna().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [68]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             101766 non-null  object
 23  A1Cresult                 101766 non-null  object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB